export type ProductPage = {
  slug: string; eyebrow: string; title: string; summary: string; proof: string;
  benefits: Array<{ title: string; body: string }>;
  details: Array<{ label: string; value: string }>;
  related: string[];
};

export type OfficialIntegration = {
  id: "gmail" | "slack" | "discord";
  name: string;
  summary: string;
  capabilities: string[];
  connection: string;
};

export const officialIntegrations: OfficialIntegration[] = [
  {
    id: "gmail",
    name: "Gmail",
    summary:
      "Watch messages, create drafts, send email, and organise threads with labels through a scoped OAuth connection.",
    capabilities: ["Email", "Drafts", "Labels"],
    connection: "OAuth 2.0 + PKCE",
  },
  {
    id: "slack",
    name: "Slack",
    summary:
      "Send focused channel alerts through an incoming webhook kept in the operating-system credential store.",
    capabilities: ["Messages", "Webhooks", "Alerts"],
    connection: "Incoming webhook",
  },
  {
    id: "discord",
    name: "Discord",
    summary:
      "Post messages and rich embeds for workflow results, incidents, and scheduled status updates.",
    capabilities: ["Messages", "Embeds", "Webhooks"],
    connection: "Incoming webhook",
  },
];

export const productPages: ProductPage[] = [
  { slug:"visual-workflow-builder", eyebrow:"Visual workflow builder", title:"Build the logic. See the consequences.", summary:"Connect typed nodes for triggers, browser actions, files, APIs, conditions and notifications. Test each step before the workflow becomes operational.", proof:"The desktop editor validates connection types, permissions and cycles before a run can start.", benefits:[{title:"Make branching explicit",body:"True and false paths stay visible, with skipped branches explained in execution history."},{title:"Map structured data",body:"Reference earlier node outputs without hiding transformations in a black box."},{title:"Publish with intent",body:"Keep drafts separate from approved versions and return to an earlier revision when needed."}], details:[{label:"Editor",value:"Desktop application"},{label:"Connections",value:"Typed and validated"},{label:"Testing",value:"Manual node and workflow runs"},{label:"History",value:"Versioned revisions"}], related:["workflows/editor","workflows/data-mapping","workflows/versions"] },
  { slug:"local-automation", eyebrow:"Local automation", title:"Automate the machine in front of you.", summary:"Move files, run approved commands, call private APIs and respond to local schedules without sending the workflow or its data through a hosted task service.", proof:"Filesystem paths are restricted to approved roots, command execution uses explicit executables and argument arrays, and sensitive values are redacted from logs.", benefits:[{title:"Reach what cloud tools cannot",body:"Use LAN services, local folders and applications that are unavailable from the public internet."},{title:"Keep control local",body:"Credentials stay in the operating-system vault and workflows can run without an account."},{title:"No local task tax",body:"Workflows executed entirely on your machines are not charged per task."}], details:[{label:"Files",value:"Approved roots only"},{label:"Commands",value:"Explicit approval required"},{label:"Private APIs",value:"Domain-restricted HTTP"},{label:"Schedules",value:"Durable local schedules"}], related:["getting-started/run-locally","nodes/system","connections/credential-security"] },
  { slug:"browser-automation", eyebrow:"Browser automation", title:"Record browser work. Keep every step editable.", summary:"Capture navigation, clicks, fields and downloads in managed Chromium, then turn the recording into ordinary workflow nodes you can inspect and change.", proof:"Recorded locators use semantic candidates and fallbacks. Failures can preserve screenshots and bounded diagnostics without exposing protected field values.", benefits:[{title:"Start from real behaviour",body:"Use the recorder to capture repetitive steps rather than reconstructing them from memory."},{title:"Extract structured results",body:"Collect text, attributes or repeated fields for the rest of the workflow."},{title:"Diagnose the failure",body:"See the failed locator, timing, screenshot and retry decision in one execution view."}], details:[{label:"Profiles",value:"Managed, isolated sessions"},{label:"Recorder",value:"Editable node output"},{label:"Downloads",value:"Size and folder controls"},{label:"Execution",value:"Local or managed worker"}], related:["browser-automation/recorder","browser-automation/locators","browser-automation/troubleshooting"] },
  { slug:"always-on-execution", eyebrow:"Always-on execution", title:"Move from a laptop to durable infrastructure.", summary:"Deploy a published workflow to hosted workers, your server, a NAS or an ARM64 machine while keeping runner identity, scheduling and recovery visible.", proof:"Runner heartbeats, leases, checkpoints and deterministic pool routing are implemented in the control plane and server agent.", benefits:[{title:"Choose per environment",body:"Use local development, a staging runner and an isolated production pool."},{title:"Recover deliberately",body:"Checkpointed executions distinguish retryable work from terminal failures."},{title:"Operate one fleet",body:"See runner status, version, capacity and assigned workloads in a shared control plane."}], details:[{label:"Hosted",value:"Isolated runner workers"},{label:"Self-hosted",value:"Linux x64 and ARM64"},{label:"Pools",value:"Deterministic routing"},{label:"Schedules",value:"Durable queue"}], related:["execution/self-hosted-runner","execution/runner-pools","execution/failure-recovery"] },
  { slug:"plugins-marketplace", eyebrow:"Plugins and marketplace", title:"Extend the platform without granting the world.", summary:"Install signed, version-pinned plugins whose declared capabilities can be reviewed before any node becomes available.", proof:"Plugin packages run as WebAssembly components behind a host capability broker; network domains and other permissions are declared in the manifest.", benefits:[{title:"Review before install",body:"Inspect publisher identity, nodes, network domains and requested capabilities."},{title:"Pin what runs",body:"Workflow revisions record an exact plugin version and package integrity."},{title:"Keep private work private",body:"Organisation plugins use scoped visibility and the same reviewable manifest model."}], details:[{label:"Runtime",value:"Capability-controlled WebAssembly"},{label:"Integrity",value:"Signed immutable packages"},{label:"Versions",value:"Exact workflow pins"},{label:"Publishers",value:"First-party, verified or community"}], related:["plugins/introduction","plugins/permissions","plugins/publishing"] },
  { slug:"teams-governance", eyebrow:"Teams and governance", title:"Share the workflow. Keep operational control.", summary:"Coordinate workspaces, published revisions, approvals, shared connections and runners without turning every contributor into an administrator.", proof:"Built-in roles and permission checks cover workflow publication, member management, runner control, marketplace approval and audit access.", benefits:[{title:"Separate draft from production",body:"Require review before a workflow revision becomes deployable."},{title:"Deploy shared connections",body:"Scope credentials to environments, workflows and roles."},{title:"Trace administrative changes",body:"Use audit history for member, policy, runner and publication actions."}], details:[{label:"Roles",value:"Built-in permission sets"},{label:"Approvals",value:"Revision publication gates"},{label:"Connections",value:"Environment scoped"},{label:"Audit",value:"Workspace event history"}], related:["teams/roles","teams/approvals","teams/audit-log"] },
  { slug:"developers", eyebrow:"Developer platform", title:"Automate through code when code is the right interface.", summary:"Build plugins, package workflow definitions and operate self-hosted runners with versioned schemas and command-line tooling.", proof:"The repository includes a typed v1 API client, validated OpenAPI specification, plugin SDK, workflow contracts and an authenticated runner protocol.", benefits:[{title:"Create focused nodes",body:"Use the plugin SDK to define configuration, inputs, outputs and capabilities."},{title:"Integrate against a versioned contract",body:"Generate clients from the validated OpenAPI document or use the maintained typed TypeScript client."},{title:"Operate your infrastructure",body:"Pair signed runners and deploy workflows through versioned control-plane contracts."}], details:[{label:"Plugin SDK",value:"TypeScript and Rust guest examples"},{label:"CLI",value:"Scaffold, validate and package"},{label:"Schemas",value:"Versioned contracts"},{label:"Public API",value:"Versioned v1 beta contract"}], related:["plugins/sdk-setup","developers/api","developers/cli"] },
];

export const useCases = [
  {slug:"browser-automation",title:"Turn a repeated browser routine into an inspectable workflow",problem:"Reports often live behind interactive sites that expose no useful API.",nodes:"Schedule → Open browser → Navigate → Download file → Condition → Notification",target:"This computer or managed browser worker",difficulty:"Intermediate",permissions:"Browser profile, approved download folder and target domains",result:"A dated report is downloaded and a failure includes a screenshot."},
  {slug:"file-folder-automation",title:"Keep incoming folders organised without uploading their contents",problem:"Downloads and inbound files require predictable naming, validation and routing.",nodes:"File watch → Condition → Move file → Notification",target:"This computer, NAS or self-hosted runner",difficulty:"Starter",permissions:"Read and write access to selected folders",result:"Matching files are moved locally and every action appears in run history."},
  {slug:"website-monitoring",title:"Check a private or public page on a schedule",problem:"Important pages change or fail without a reliable signal.",nodes:"Schedule → HTTP request → Condition → Discord webhook",target:"Local, hosted or self-hosted runner",difficulty:"Starter",permissions:"Target domain and notification connection",result:"Only meaningful status changes produce a notification."},
  {slug:"report-collection",title:"Collect recurring reports before the workday starts",problem:"Teams repeatedly sign in, download reports and check whether the result is usable.",nodes:"Schedule → Open browser → Download → Extract data → Condition → Slack webhook",target:"Managed browser worker or trusted local machine",difficulty:"Intermediate",permissions:"Browser profile, download folder and Slack connection",result:"A verified report is ready, with evidence when collection fails."},
  {slug:"developer-workflows",title:"Join local commands and HTTP services in one visible run",problem:"Small release and maintenance routines become fragile collections of scripts.",nodes:"Manual trigger → Run command → HTTP request → Condition → Notification",target:"Developer workstation or self-hosted runner",difficulty:"Intermediate",permissions:"Approved executable, working directory and API domain",result:"Each command, response and branch is inspectable without replacing the underlying tools."},
  {slug:"homelab-automation",title:"Automate services that never leave your private network",problem:"NAS devices, dashboards and home services are deliberately unreachable from hosted automation tools.",nodes:"Schedule → HTTP request → Condition → Discord webhook",target:"Raspberry Pi, NAS or Linux server",difficulty:"Intermediate",permissions:"Private network targets and Discord connection",result:"Local services are monitored from inside the network boundary."},
];

export const launchRelease = { version:"0.7.8-beta.1", date:"Repository state", channel:"Beta", summary:"Current repository version. No public download artifact is attached to this source state.", availableArtifacts:[] as Array<{platform:string;architecture:string;url:string;size:string;checksum:string;signature:string}> };

export const legalPages = ["terms","privacy","cookies","acceptable-use","marketplace-terms","publisher-terms","data-processing-addendum","subprocessors","vulnerability-disclosure","refunds","accessibility","complaints"] as const;

export type TransactionalEmail = { key:string; subject:string; html:(values:Record<string,string>)=>string; text:(values:Record<string,string>)=>string };
const email = (key:string,subject:string,heading:string,body:string):TransactionalEmail => ({key,subject,html:values=>`<!doctype html><html><body style="margin:0;background:#08090a;color:#f2f4f5;font-family:Arial,sans-serif"><main style="max-width:560px;margin:auto;padding:40px 24px"><p style="color:#d6ff4b;font-size:12px">sndbox</p><h1 style="font-size:24px">${heading}</h1><p style="color:#a4abb2;line-height:1.6">${body.replace(/\{(\w+)\}/g,(_,name)=>values[name]??`{${name}}`)}</p><p style="color:#626a72;font-size:11px">This is a transactional account message.</p></main></body></html>`,text:values=>`sndbox\n\n${heading}\n\n${body.replace(/\{(\w+)\}/g,(_,name)=>values[name]??`{${name}}`)}\n\nThis is a transactional account message.`});
export const transactionalEmails=[email("welcome","Welcome to sndbox","Welcome to sndbox","Your account is ready. Download a verified build from {downloadUrl}."),email("verify-email","Verify your sndbox email","Verify your email","Open this time-limited link to verify your email: {verifyUrl}"),email("download-link","Your sndbox download link","Your download is ready","This signed link expires at {expiresAt}: {downloadUrl}"),email("purchase-receipt","sndbox purchase receipt","Purchase confirmed","Receipt {receiptId} is available in your account: {accountUrl}"),email("renewal","sndbox renewal confirmation","Subscription renewed","Your {plan} plan renewed on {renewalDate}."),email("payment-failure","Action needed: sndbox payment failed","Payment failed","Update your payment method by {deadline}: {billingUrl}"),email("trial-ending","Your sndbox trial is ending","Trial ending","Your trial ends on {endDate}. Local workflows remain on your machine."),email("licence-assignment","A sndbox licence was assigned to you","Licence assigned","{owner} assigned a {plan} licence to you."),email("support-opened","sndbox support case {caseId}","Support case opened","We received {caseId}. Reply in the protected support portal: {caseUrl}"),email("support-reply","Reply on sndbox support case {caseId}","Support replied","A new reply is available in the protected portal: {caseUrl}"),email("release","sndbox {version} is available","New sndbox release","Review release notes and verified downloads: {releaseUrl}"),email("security-update","sndbox security update","Security update","Read the security notice and required action: {noticeUrl}"),email("enterprise-confirmation","sndbox enterprise enquiry received","Enquiry received","Your reference is {correlationId}. Our team will reply to this email address.")];
